name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers for testing
  workflow_call:  # Allow other repos to call this workflow
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      with-summaries:
        description: 'Generate AI summaries'
        required: false
        type: boolean
        default: true
      model:
        description: 'LLM model to use'
        required: false
        type: string
        default: 'claude-3-5-haiku-20241022'
      use-openai:
        description: 'Use OpenAI instead of Anthropic'
        required: false
        type: boolean
        default: false
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for AI summaries'
        required: false
      OPENAI_API_KEY:
        description: 'OpenAI API key (alternative to Anthropic)'
        required: false

jobs:
  changelog:
    runs-on: ubuntu-latest

    # Skip if commit message contains [skip ci] or [changelog skip]
    # Only apply this check when triggered by push (not workflow_call)
    if: "github.event_name == 'workflow_call' || (!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[changelog skip]'))"

    permissions:
      contents: write  # Required to create branches and commits
      pull-requests: write  # Required to create PRs
      actions: read  # Required to read workflow runs

    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history to find last changelog commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout changelog_generator for changelog script
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/changelog_generator
          path: .changelog_generator
          sparse-checkout: |
            changelog/run.py

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.11' }}

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate changelog
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .changelog_generator/changelog/run.py \
            --since-last-commit \
            --write \
            ${{ inputs.with-summaries && '--with-summaries' || '' }} \
            ${{ inputs.use-openai && '--use-openai' || '' }} \
            --model ${{ inputs.model || 'claude-3-5-haiku-20241022' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update changelog [skip ci]"
          committer: changelog-bot <changelog-bot@users.noreply.github.com>
          author: changelog-bot <changelog-bot@users.noreply.github.com>
          title: "chore: update changelog"
          body: |
            ## 🤖 Automated Changelog Update

            This PR updates the changelog with recently merged PRs.

            **Changes:**
            - Updated `CHANGELOG.md` with latest entries
            - Updated `.changelog-summaries.json` cache (if AI summaries enabled)

            **Generated by:** changelog-bot
            **Triggered by:** Merge to main

            ---
            *This PR will auto-merge if auto-merge is enabled and all checks pass.*
          branch: changelog-updates
          base: main
          delete-branch: true
          labels: |
            automated
            documentation
          token: ${{ secrets.GITHUB_TOKEN }}
